### ISSUE TITLE
Cryptology ePrint Archive: BibTeX Citation of Report 2015/967 @misc{cryptoeprint:2015:967,     author = {Marc Stevens and Pierre Karpman and Thomas Peyrin},     title = {Freestart collision for full SHA-1},     howpublished = {Cryptology ePrint Archive, Report 2015/967},     year = {2015},     note = {\url{https://eprint.iacr.org/2015/967}}, } You will need the url.sty package (comes with most LaTeX installations) for the last line. Otherwise, remove the \url command.  [ Cryptology ePrint archive ]

### ISSUE THREAD

**Issue by Monareyes628l** [CreateJS/SoundJS#290]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [ ] Did you search the [issues](https://github.com/CreateJS/SoundJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/SoundJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

* Do you know of any workarounds?

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by Monareyes628l** [comment]
Code  Issues 69  Pull requests 2  Pulse
Jump to bottom Closed
Cryptology ePrint Archive: BibTeX Citation of Report 2015/967 @misc{cryptoeprint:2015:967, author = {Marc Stevens and Pierre Karpman and Thomas Peyrin}, title = {Freestart collision for full SHA-1}, howpublished = {Cryptology ePrint Archive, Report 2015/967}, year = {2015}, note = {\url{https://eprint.iacr.org/2015/967}}, } You will need the url.sty package (comes with most LaTeX installations) for the last line. Otherwise, remove the \url command. [ Cryptology ePrint archive ] #290
@Monareyes628l
Monareyes628l opened this issue 
4 minutes ago 
TODO
 Is this a question or bug? Stack Overflow is a much better place to ask any questions you may have.

 Did you search the issues to see if someone else has already reported your issue? If yes, please add more details if you have any!

 If you're using an older version, have you tried the latest?

 If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

Issue Details
Version used (Ex; 1.0):

Describe whats happening (Include any relevant console errors, a Gist is preferred for longer errors):

OS & Browser version (Please be specific) (Ex; Windows 10 Home, Chrome 62.0.3202.94):

Do you know of any workarounds?

Provide any extra details that will help us fix your issue. Including a link to a CodePen.io or JSFiddle.net example that shows the issue in isolation will greatly increase the chance of getting a quick response.

gskinner closed this issue 4 minutes ago
Comment on issue
 
Leave a comment
Comment
Notifications for this thread
You’re receiving notifications because you authored the thread.

  Unsubscribe
 Desktop version
