### ISSUE TITLE
i get this error: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

### ISSUE THREAD

**Issue by kh83** [CreateJS/SoundJS#310]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [ ] Did you search the [issues](https://github.com/CreateJS/SoundJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/SoundJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

* Do you know of any workarounds?

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by lannymcnie** [comment]
Google changed some browser behaviours to prevent "automatic" audio playback without user interaction, much like mobile. Tracking it here: #297

**Comment by kh83** [comment]
Thanx a lot for the quick replyL😉

 

Fra: Lanny McNie <notifications@github.com> 
Sendt: torsdag 1. november 2018 13:48
Til: CreateJS/SoundJS <SoundJS@noreply.github.com>
Kopi: kh83 <kh.aarnes@gmail.com>; Author <author@noreply.github.com>
Emne: Re: [CreateJS/SoundJS] i get this error: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD (#310)

 

Google changed some browser behaviours to prevent "automatic" audio playback without user interaction, much like mobile. Tracking it here: #297 <https://github.com/CreateJS/SoundJS/issues/297>
